packages:
  - 'packages/*'
  - 'servers/*'
allowBuilds:
  esbuild: true
  protobufjs: true
  sharp: true
  tree-sitter: true
  tree-sitter-c: true
  tree-sitter-cpp: true
  tree-sitter-go: true
  tree-sitter-java: true
  tree-sitter-javascript: true
  tree-sitter-python: true
  tree-sitter-rust: true
  tree-sitter-typescript: true
